# Answer 1

Min-Max scaling, also known as feature scaling or normalization, is a data preprocessing technique used to scale and transform the values of numerical features within a specific range. The goal is to bring all the features to a similar scale, preventing some features from dominating others due to differences in their original magnitudes. This is particularly important for machine learning algorithms that are sensitive to the scale of input features, such as gradient descent-based methods.

The formula for Min-Max scaling is as follows:

 X_((scaled)) = (X - X_((min))) / (X_((max)) - X_((min))) 

Where:
-  X_((scaled))  is the scaled value of the feature.
-  X  is the original value of the feature.
-  X_((min))  is the minimum value of the feature in the dataset.
-  X_((max))  is the maximum value of the feature in the dataset.

The resulting scaled values will fall within the range [0, 1].

In below example, the `MinMaxScaler` from scikit-learn is used to scale the dataset. The `fit_transform` method computes the minimum and maximum values of each feature in the dataset and scales the values accordingly. The resulting `scaled_data` will have values between 0 and 1.

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)

print("Original data:\n", data)
print("Scaled data:\n", scaled_data)

Original data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Scaled data:
 [[0.  0.  0. ]
 [0.5 0.5 0.5]
 [1.  1.  1. ]]


# Answer 2

The Unit Vector technique, also known as vector normalization or unit normalization, is a feature scaling method that scales the values of a feature to have a unit norm. The unit norm is the Euclidean norm (L2 norm) of a vector, which is the square root of the sum of the squared elements. The purpose of unit normalization is to ensure that the magnitude of each feature vector is equal to 1.

The formula for Unit Vector scaling is as follows:

 X_((unit)) = (X) / (||X||_2) 

Where:
-  X_((unit))  is the unit-scaled vector.
-  X  is the original vector of feature values.
-  ||X||_2  is the Euclidean norm of the vector  X .

Unlike Min-Max scaling, which scales the values of each feature to a specific range (e.g., [0, 1]), Unit Vector scaling focuses on the direction of the vector, not the magnitude.

In below example, the `Normalizer` from scikit-learn is used with the L2 norm. The `transform` method normalizes each row (feature vector) in the dataset to have a unit norm. The resulting `unit_scaled_data` will have feature vectors with a magnitude of 1.

In [2]:
import numpy as np
from sklearn.preprocessing import Normalizer
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

normalizer = Normalizer(norm='l2')
unit_scaled_data = normalizer.transform(data)
print("Original data:\n", data)
print("Unit Vector scaled data:\n", unit_scaled_data)

Original data:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Unit Vector scaled data:
 [[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]


# Answer 3

Principal Component Analysis (PCA) is a dimensionality reduction technique that is commonly used in machine learning and data analysis. The main goal of PCA is to transform a dataset into a new coordinate system, where the axes are the principal components, and the data is represented in terms of these components. The principal components are linear combinations of the original features, and they are arranged in descending order of variance. By retaining only the top k principal components, where k is a user-defined parameter, PCA reduces the dimensionality of the data while preserving most of its variability.

The steps involved in PCA are as follows:

1. Standardize the data: If the features are on different scales, it's common practice to standardize the data (subtract mean and divide by standard deviation).

2. Compute the covariance matrix: Calculate the covariance matrix of the standardized data.

3. Compute eigenvectors and eigenvalues: Find the eigenvectors and eigenvalues of the covariance matrix. The eigenvectors represent the principal components, and the eigenvalues indicate the amount of variance captured by each component.

4. Sort and select top k components: Sort the eigenvectors by their corresponding eigenvalues in descending order. Choose the top k eigenvectors to form the new feature subspace.

5. Transform the data: Use the selected eigenvectors to transform the original data into the new feature space.

In below example, PCA is applied to the Iris dataset. The data is standardized, and then PCA is used to transform it into a new space with only 2 principal components. The resulting `X_pca` contains the data in this reduced-dimensional space.

In [3]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

X_standardized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_standardized)

print("Original data shape:", X_standardized.shape)
print("Transformed data shape:", X_pca.shape)

Original data shape: (150, 4)
Transformed data shape: (150, 2)


# Answer 4

PCA (Principal Component Analysis) is closely related to feature extraction, and in fact, PCA is a specific technique for feature extraction. Feature extraction is a broader concept that encompasses various methods to transform and represent the original features of a dataset in a different, often more compact, and informative way. PCA is one such technique for feature extraction, and it specifically focuses on capturing the most significant patterns in the data by identifying principal components.

Below is how PCA can be used for feature extraction:

1. **Linear Combination of Features:**
   - PCA identifies linear combinations of the original features, known as principal components.
   - These principal components are orthogonal to each other and are ranked by the amount of variance they capture in the data.

2. **Dimensionality Reduction:**
   - By selecting a subset of the top principal components, PCA reduces the dimensionality of the dataset.
   - This reduction in dimensionality is a form of feature extraction, as it transforms the original features into a smaller set of more meaningful components.

3. **Preservation of Variance:**
   - PCA retains as much variance in the data as possible in the reduced-dimensional space.
   - The first few principal components capture the most significant sources of variability in the data, providing a compact representation.

In this example, PCA is applied to the Iris dataset, and the number of components is set to 2. The resulting `X_features` contains the data in a reduced-dimensional space, where the original features have been effectively transformed into two principal components.

In [4]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target

X_standardized = (X - np.mean(X, axis=0)) / np.std(X, axis=0)

pca = PCA(n_components=2)  # Reduce to 2 dimensions
X_features = pca.fit_transform(X_standardized)

print("Original data shape:", X_standardized.shape)
print("Transformed data shape (after feature extraction):", X_features.shape)

Original data shape: (150, 4)
Transformed data shape (after feature extraction): (150, 2)


# Answer 5

The goal is to standardize the range of values for each feature, ensuring that they fall within a specific interval (typically [0, 1]). By applying Min-Max scaling, we ensure that the features with different scales (e.g., price in dollars and rating on a scale of 1 to 5) are transformed to a common scale, making them comparable. This is important for recommendation systems, as it prevents features with larger magnitudes from dominating the recommendation process.

1. **Understand the Data:**
   - Examine the range of values for each feature in the dataset (price, rating, delivery time).
   - Identify if there are significant differences in the magnitudes of these features.

2. **Import Necessary Libraries:**
   - In Python, we might use libraries such as NumPy or scikit-learn for Min-Max scaling. Here's an example using scikit-learn:

     ```python
     from sklearn.preprocessing import MinMaxScaler
     ```

3. **Standardize the Data:**
   - Create an instance of the `MinMaxScaler` class.
   - Apply the `fit_transform` method to scale the features within the desired range.

     ```python
     # Assuming 'data' is your dataset with columns for price, rating, and delivery time
     scaler = MinMaxScaler()
     scaled_data = scaler.fit_transform(data)
     ```

4. **Check the Scaled Data:**
   - Inspect the resulting scaled data to ensure that the values are now within the [0, 1] range.

     ```python
     print("Original data:\n", data)
     print("Scaled data:\n", scaled_data)
     ```

5. **Updated Dataset:**
   - Replace the original values with the scaled values in your dataset.

     ```python
     data['price'] = scaled_data[:, 0]  # Assuming price is the first column
     data['rating'] = scaled_data[:, 1]  # Assuming rating is the second column
     data['delivery_time'] = scaled_data[:, 2]  # Assuming delivery time is the third column
     ```

# Answer 6

When working on a project to predict stock prices with a dataset containing numerous features like company financial data and market trends, Principal Component Analysis (PCA) can be used to reduce the dimensionality of the dataset. Dimensionality reduction is beneficial in this context for several reasons, including mitigating the curse of dimensionality, simplifying the model, and potentially improving the model's generalization performance.

1. **Data Preprocessing:**
   - Handle missing values, outliers, and any other data preprocessing steps as needed.
   - Standardize the features to ensure that they have a mean of 0 and a standard deviation of 1. This step is essential for PCA, as it is sensitive to the scale of the features.

2. **Apply PCA:**
   - Import the necessary libraries, such as scikit-learn in Python:

     ```python
     from sklearn.decomposition import PCA
     from sklearn.preprocessing import StandardScaler
     ```

   - Standardize the data:

     ```python
     # Assuming 'data' with multiple features
     scaler = StandardScaler()
     standardized_data = scaler.fit_transform(data)
     ```

   - Apply PCA to the standardized data:

     ```python
     # Choose the number of components
     pca = PCA(n_components=5)
     reduced_data = pca.fit_transform(standardized_data)
     ```

   - The `n_components` parameter specifies the number of principal components to retain. we can choose this value based on the desired level of dimensionality reduction.

3. **Explained Variance:**
   - Analyze the explained variance to understand how much of the total variance in the original dataset is retained by each principal component:

     ```python
     explained_variance_ratio = pca.explained_variance_ratio_
     print("Explained Variance Ratio:", explained_variance_ratio)
     ```

   - This information helps we decide how many principal components to retain. we may choose a number that retains a significant portion of the variance, such as 95% or 99%.

4. **Select Number of Components:**
   - Based on the analysis of explained variance, choose the appropriate number of principal components that retain a sufficient amount of information.

5. **Update Dataset:**
   - Use the selected number of principal components to update your dataset:

     ```python
     # 'new_data' is your updated dataset with reduced dimensionality
     new_data = reduced_data[:, :chosen_number_of_components]
     ```

   - This reduced dataset can then be used as input for your stock price prediction model.

# Answer 7

In [6]:
import numpy as np

def min_max_scale(data):
    x_norm = (data - np.min(data)) / (np.max(data) - np.min(data))
    x_scaled = 2 * x_norm - 1
    return x_scaled

data = np.array([1, 5, 10, 15, 20])
scaled_data = min_max_scale(data)
print(scaled_data)

[-1.         -0.57894737 -0.05263158  0.47368421  1.        ]


# Answer 8

The decision on how many principal components to retain during Feature Extraction using PCA involves a trade-off between reducing dimensionality and retaining a sufficient amount of variance in the data. The goal is to capture as much information as possible with a smaller set of features. 

The rationale for choosing the number of principal components depends on the application and the desired balance between dimensionality reduction and information preservation. Retaining more components captures more information but might increase computational complexity, while retaining fewer components simplifies the model but may lose some information. Below are the steps we can follow to determine the number of principal components to retain:

1. **Standardize the Data:**
   - Before applying PCA, it's important to standardize the data to ensure that all features are on the same scale.

2. **Apply PCA:**
   - Use PCA to transform the standardized data and compute the principal components.

   ```python
   from sklearn.decomposition import PCA
   from sklearn.preprocessing import StandardScaler

   # Assuming 'data' is dataset with columns for height, weight, age, gender, blood pressure
   scaler = StandardScaler()
   standardized_data = scaler.fit_transform(data)

   pca = PCA()
   principal_components = pca.fit_transform(standardized_data)
   ```

3. **Explained Variance:**
   - Analyze the explained variance ratio to understand how much variance is captured by each principal component.

   ```python
   explained_variance_ratio = pca.explained_variance_ratio_
   ```

4. **Cumulative Explained Variance:**
   - Calculate the cumulative explained variance to see how much variance is explained as we include more principal components.

   ```python
   cumulative_explained_variance = np.cumsum(explained_variance_ratio)
   ```

5. **Choose the Number of Components:**
   - Decide on the number of principal components to retain based on the cumulative explained variance and your desired threshold.
   - Common choices include retaining enough components to explain 90%, 95%, or 99% of the total variance.

   ```python
   # Retaining components explaining 95% of the variance
   n_components = np.argmax(cumulative_explained_variance >= 0.95) + 1
   ```

6. **Update Dataset:**
   - Use the selected number of principal components to update your dataset.

   ```python
   # 'new_data' is updated dataset with reduced dimensionality
   new_data = principal_components[:, :n_components]
   ```