# Answer 1

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_: ", type(list_[0]))
print("Data type of array_list: ", array_list.dtype)


Data type of list_:  <class 'str'>
Data type of array_list:  <U1


# Answer 2

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_: ", [type(item) for item in list_])
print("Data types of elements in array_list: ", array_list.dtype)


Data types of elements in list_:  [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types of elements in array_list:  <U1


# Answer 3

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data types of elements in list_ before change: ", [type(item) for item in list_])
print("Data types of elements in array_list before change: ", array_list.dtype)

# Change
array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_ after change: ", [type(item) for item in list_])
print("Data types of elements in array_list after change: ", array_list.dtype)


Data types of elements in list_ before change:  [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types of elements in array_list before change:  <U1
Data types of elements in list_ after change:  [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data types of elements in array_list after change:  int32


# Answer 4

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) shape
print("Shape of num_array:", num_array.shape)

# (ii) size
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


# Answer 5

In [5]:
import numpy as np

zeros_array = np.zeros((3, 3))
print("3x3 Matrix of Zeros:")
print(zeros_array)

3x3 Matrix of Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Answer 6

In [6]:
import numpy as np

identity_matrix = np.eye(5)
print("Identity Matrix of shape (5,5):")
print(identity_matrix)

Identity Matrix of shape (5,5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
